#ifndef svpwm_inv_ideal_switch_Motor_DVS_new_param_capi_h_
#define svpwm_inv_ideal_switch_Motor_DVS_new_param_capi_h_
#include "svpwm_inv_ideal_switch_Motor_DVS_new_param.h"
extern void svpwm_inv_ideal_switch_Motor_DVS_new_param_InitializeDataMapInfo
( void ) ;
#endif
