#include "ext_types.h"
static DataTypeInfo rtDataTypeInfoTable [ ] = { { "real_T" , 0 , 8 } , {
"real32_T" , 1 , 4 } , { "int8_T" , 2 , 1 } , { "uint8_T" , 3 , 1 } , {
"int16_T" , 4 , 2 } , { "uint16_T" , 5 , 2 } , { "int32_T" , 6 , 4 } , {
"uint32_T" , 7 , 4 } , { "boolean_T" , 8 , 1 } , { "fcn_call_T" , 9 , 0 } , {
"int_T" , 10 , 4 } , { "pointer_T" , 11 , 8 } , { "action_T" , 12 , 8 } , {
"timer_uint32_pair_T" , 13 , 8 } , { "physical_connection" , 14 , 8 } , {
"int64_T" , 15 , 8 } , { "uint64_T" , 16 , 8 } , {
"struct_7U2Xy3czgmwuE6XJcblrBG" , 17 , 16 } , {
"struct_Ls6rPOlOdPa13bKCSJdtDG" , 18 , 8 } , { "uint64_T" , 19 , 8 } , {
"int64_T" , 20 , 8 } , { "uint_T" , 21 , 32 } , { "char_T" , 22 , 8 } , {
"uchar_T" , 23 , 8 } , { "time_T" , 24 , 8 } } ; static uint_T
rtDataTypeSizes [ ] = { sizeof ( real_T ) , sizeof ( real32_T ) , sizeof ( int8_T ) , sizeof ( uint8_T ) , sizeof ( int16_T ) , sizeof ( uint16_T ) , sizeof ( int32_T ) , sizeof ( uint32_T ) , sizeof ( boolean_T ) , sizeof ( fcn_call_T ) , sizeof ( int_T ) , sizeof ( pointer_T ) , sizeof ( action_T ) , 2 * sizeof ( uint32_T ) , sizeof ( int32_T ) , sizeof ( int64_T ) , sizeof ( uint64_T ) , sizeof ( struct_7U2Xy3czgmwuE6XJcblrBG ) , sizeof ( struct_Ls6rPOlOdPa13bKCSJdtDG ) , sizeof ( uint64_T ) , sizeof ( int64_T ) , sizeof ( uint_T ) , sizeof ( char_T ) , sizeof ( uchar_T ) , sizeof ( time_T ) } ; static const char_T * rtDataTypeNames [ ] = { "real_T" , "real32_T" , "int8_T" , "uint8_T" , "int16_T" , "uint16_T" , "int32_T" , "uint32_T" , "boolean_T" , "fcn_call_T" , "int_T" , "pointer_T" , "action_T" , "timer_uint32_pair_T" , "physical_connection" , "int64_T" , "uint64_T" , "struct_7U2Xy3czgmwuE6XJcblrBG" , "struct_Ls6rPOlOdPa13bKCSJdtDG" , "uint64_T" , "int64_T" , "uint_T" , "char_T" , "uchar_T" , "time_T" } ; static DataTypeTransition rtBTransitions [ ] = { { ( char_T * ) ( & rtB . f4xms5nl2i ) , 0 , 0 , 162 } , { ( char_T * ) ( & rtB . gb350culcr ) , 5 , 0 , 2 } , { ( char_T * ) ( & rtB . eixa3whjg5 ) , 8 , 0 , 5 } , { ( char_T * ) ( & rtDW . gryfwaapqt [ 0 ] ) , 0 , 0 , 48 } , { ( char_T * ) ( & rtDW . hrvru3xtvt ) , 11 , 0 , 99 } , { ( char_T * ) ( & rtDW . onbaoth1i5 ) , 6 , 0 , 3 } , { ( char_T * ) ( & rtDW . nlxub2bocz ) , 10 , 0 , 49 } , { ( char_T * ) ( & rtDW . ohklipqz2o ) , 6 , 0 , 1 } , { ( char_T * ) ( & rtDW . dzjyg0fd1v ) , 2 , 0 , 6 } , { ( char_T * ) ( & rtDW . ax5d3atq5l ) , 3 , 0 , 12 } , { ( char_T * ) ( & rtDW . ldoy1brot0 ) , 8 , 0 , 26 } , { ( char_T * ) ( & rtDW . oicpqfoumb . ejurx0a1nn ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . lykvoxa5oj . anoxqeev0m ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . bs1lyechiq . ejurx0a1nn ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . jm1szxhn3j . anoxqeev0m ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . bh2lhy5mc2 . ejurx0a1nn ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . dj3tel0mec . anoxqeev0m ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . en1etzgb25t . ejurx0a1nn ) , 2 , 0 , 1 } , { ( char_T * ) ( & rtDW . hdua2qktjg2 . anoxqeev0m ) , 2 , 0 , 1 } } ; static DataTypeTransitionTable rtBTransTable = { 19U , rtBTransitions } ; static DataTypeTransition rtPTransitions [ ] = { { ( char_T * ) ( & rtP . FocDiscrTime ) , 0 , 0 , 4162 } , { ( char_T * ) ( & rtP . offset_Value [ 0 ] ) , 4 , 0 , 16 } , { ( char_T * ) ( & rtP . Offset_Value ) , 5 , 0 , 8 } , { ( char_T * ) ( & rtP . Constant_Value_c2e1y2gzc3 ) , 2 , 0 , 16 } } ; static DataTypeTransitionTable rtPTransTable = { 4U , rtPTransitions } ;
