#include "ext_types.h"
static DataTypeInfo rtDataTypeInfoTable [ ] = { { "real_T" , 0 , 8 } , {
"real32_T" , 1 , 4 } , { "int8_T" , 2 , 1 } , { "uint8_T" , 3 , 1 } , {
"int16_T" , 4 , 2 } , { "uint16_T" , 5 , 2 } , { "int32_T" , 6 , 4 } , {
"uint32_T" , 7 , 4 } , { "boolean_T" , 8 , 1 } , { "fcn_call_T" , 9 , 0 } , {
"int_T" , 10 , 4 } , { "pointer_T" , 11 , 8 } , { "action_T" , 12 , 8 } , {
"timer_uint32_pair_T" , 13 , 8 } , { "physical_connection" , 14 , 8 } , {
"int64_T" , 15 , 8 } , { "uint64_T" , 16 , 8 } , {
"struct_Ls6rPOlOdPa13bKCSJdtDG" , 17 , 8 } , {
"struct_7U2Xy3czgmwuE6XJcblrBG" , 18 , 16 } , { "uint64_T" , 19 , 8 } , {
"int64_T" , 20 , 8 } , { "uint_T" , 21 , 32 } , { "char_T" , 22 , 8 } , {
"uchar_T" , 23 , 8 } , { "time_T" , 24 , 8 } } ; static uint_T
rtDataTypeSizes [ ] = { sizeof ( real_T ) , sizeof ( real32_T ) , sizeof ( int8_T ) , sizeof ( uint8_T ) , sizeof ( int16_T ) , sizeof ( uint16_T ) , sizeof ( int32_T ) , sizeof ( uint32_T ) , sizeof ( boolean_T ) , sizeof ( fcn_call_T ) , sizeof ( int_T ) , sizeof ( pointer_T ) , sizeof ( action_T ) , 2 * sizeof ( uint32_T ) , sizeof ( int32_T ) , sizeof ( int64_T ) , sizeof ( uint64_T ) , sizeof ( struct_Ls6rPOlOdPa13bKCSJdtDG ) , sizeof ( struct_7U2Xy3czgmwuE6XJcblrBG ) , sizeof ( uint64_T ) , sizeof ( int64_T ) , sizeof ( uint_T ) , sizeof ( char_T ) , sizeof ( uchar_T ) , sizeof ( time_T ) } ; static const char_T * rtDataTypeNames [ ] = { "real_T" , "real32_T" , "int8_T" , "uint8_T" , "int16_T" , "uint16_T" , "int32_T" , "uint32_T" , "boolean_T" , "fcn_call_T" , "int_T" , "pointer_T" , "action_T" , "timer_uint32_pair_T" , "physical_connection" , "int64_T" , "uint64_T" , "struct_Ls6rPOlOdPa13bKCSJdtDG" , "struct_7U2Xy3czgmwuE6XJcblrBG" , "uint64_T" , "int64_T" , "uint_T" , "char_T" , "uchar_T" , "time_T" } ; static DataTypeTransition rtBTransitions [ ] = { { ( char_T * ) ( & rtB . i54ue34n5x [ 0 ] ) , 0 , 0 , 107 } , { ( char_T * ) ( & rtB . mjjgcun11p ) , 8 , 0 , 3 } , { ( char_T * ) ( & rtB . m1ruyuhwwh . oxvqfiiat3 ) , 0 , 0 , 10 } , { ( char_T * ) ( & rtB . m1ruyuhwwh . htytqrpdwk ) , 5 , 0 , 1 } , { ( char_T * ) ( & rtB . ofp4g0emipz . oxvqfiiat3 ) , 0 , 0 , 10 } , { ( char_T * ) ( & rtB . ofp4g0emipz . htytqrpdwk ) , 5 , 0 , 1 } , { ( char_T * ) ( & rtDW . ijyfrnke5y [ 0 ] ) , 0 , 0 , 35 } , { ( char_T * ) ( & rtDW . l4agzxlxpz ) , 11 , 0 , 64 } , { ( char_T * ) ( & rtDW . p2brasowmj ) , 6 , 0 , 2 } , { ( char_T * ) ( & rtDW . nv5yvnrnog ) , 10 , 0 , 19 } , { ( char_T * ) ( & rtDW . jo3qsivldn ) , 6 , 0 , 1 } , { ( char_T * ) ( & rtDW . fbzzhsc0qu ) , 3 , 0 , 10 } , { ( char_T * ) ( & rtDW . jpc20qpomn ) , 8 , 0 , 18 } } ; static DataTypeTransitionTable rtBTransTable = { 13U , rtBTransitions } ; static DataTypeTransition rtPTransitions [ ] = { { ( char_T * ) ( & rtP . PIDController3_I ) , 0 , 0 , 98 } , { ( char_T * ) ( & rtP . Offset_Value ) , 5 , 0 , 4 } , { ( char_T * ) ( & rtP . Constant_Value_a2jar3lhp4 ) , 2 , 0 , 12 } , { ( char_T * ) ( & rtP . m1ruyuhwwh . Offset_Value ) , 5 , 0 , 2 } , { ( char_T * ) ( & rtP . ofp4g0emipz . Offset_Value ) , 5 , 0 , 2 } } ; static DataTypeTransitionTable rtPTransTable = { 5U , rtPTransitions } ;
